# SPDX-License-Identifier: MIT
[package]
name = "tb323fu-ctl"
description = "Command-line client for tb323fu-helperd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zbus = { workspace = true, features = ["blocking-api"] }
serde_json.workspace = true
serde.workspace = true
